'\" t
.\"     Title: mc_receive
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2014
.\"    Manual: Libmc Manual
.\"    Source: libmc 3.0.6
.\"  Language: English
.\"
.TH "MC_RECEIVE" "3" "04/02/2014" "libmc 3\&.0\&.6" "Libmc Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mc_receive \- receive a indication request
.SH "SYNOPSIS"
.sp
\fBint mc_receive(mc_t *\fR\fB\fIctx\fR\fR\fB, uint8_t *\fR\fB\fIreq\fR\fR\fB);\fR
.SH "DESCRIPTION"
.sp
The \fImc_receive()\fR function shall receive an indication request from the socket of the context \fIctx\fR\&. This function is used by Mc slave/server to receive and analyze indication request sent by the masters/clients\&.
.sp
If you need to use another socket or file descriptor than the one defined in the context \fIctx\fR, see the function \fBmc_set_socket\fR(3)\&.
.SH "RETURN VALUE"
.sp
The \fImc_receive()\fR function shall store the indication request in \fIreq\fR and return the request length if sucessful\&. Otherwise it shall return \-1 and set errno\&.
.SH "SEE ALSO"
.sp
\fBmc_set_socket\fR(3) \fBmc_reply\fR(3)
.SH "AUTHORS"
.sp
The libmc documentation was written by St\('ephane Raimbault <\m[blue]\fBstephane\&.raimbault@gmail\&.com\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "NOTES"
.IP " 1." 4
stephane.raimbault@gmail.com
.RS 4
\%mailto:stephane.raimbault@gmail.com
.RE
